In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from datetime import date, time, datetime

In [2]:
train_users = pd.read_csv("proj3_data/train_users.csv",parse_dates=['timestamp_first_active','date_account_created','date_first_booking'])
test_users = pd.read_csv("proj3_data/test_users.csv",parse_dates=['timestamp_first_active','date_account_created','date_first_booking'])
sessions = pd.read_csv("proj3_data/sessions.csv")

In [3]:
Y = train_users['country_destination']
train_users = train_users.drop('country_destination', axis =1)

In [4]:
train_users.columns

Index(['id', 'date_account_created', 'timestamp_first_active',
       'date_first_booking', 'gender', 'age', 'signup_method', 'signup_flow',
       'language', 'affiliate_channel', 'affiliate_provider',
       'first_affiliate_tracked', 'signup_app', 'first_device_type',
       'first_browser'],
      dtype='object')

In [5]:
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [6]:
#train_users.drop(['country_destination'], axis = 1)
#Concatenating train and test data for EDA
df_all = pd.concat((train_users, test_users), axis = 0, ignore_index= True)

In [7]:
df_all.age.value_counts()

30.0      7712
28.0      7687
29.0      7647
31.0      7540
27.0      7462
          ...
1954.0       1
1953.0       1
132.0        1
1937.0       1
112.0        1
Name: age, Length: 145, dtype: int64

In [8]:
from sklearn.preprocessing import MinMaxScaler

# Splitting date time data for date account created
df_all['dac_year'] = df_all.date_account_created.dt.year
df_all['dac_month'] = df_all.date_account_created.dt.month
df_all['dac_day'] = df_all.date_account_created.dt.day

# Splitting date time data for time first active
df_all['tfa_year'] = df_all.timestamp_first_active.dt.year
df_all['tfa_month'] = df_all.timestamp_first_active.dt.month
df_all['tfa_day'] = df_all.timestamp_first_active.dt.day

df_all.drop('date_account_created',1, inplace=True)
df_all.drop('timestamp_first_active',1, inplace=True)

In [9]:

#df_all.loc[df_all.age > 100, 'age'] = np.nan
#df_all.loc[df_all.age < 18, 'age'] = np.nan

age_values = df_all.age.values
df_all['age'] = np.where(age_values>1000, np.random.randint(28, 43), age_values)
df_all['age'] = df_all['age'].fillna(np.random.randint(28, 43))

In [10]:
"""
scaler = MinMaxScaler()
numerical = ['age','dac_year','dac_month','dac_day','tfa_year','tfa_month','tfa_day']
df_all[numerical] = scaler.fit_transform(df_all[numerical])"""

"\nscaler = MinMaxScaler()\nnumerical = ['age','dac_year','dac_month','dac_day','tfa_year','tfa_month','tfa_day']\ndf_all[numerical] = scaler.fit_transform(df_all[numerical])"

In [11]:
y = df_all.age.value_counts()
print(y)
print(df_all["age"].isna().sum())

33.0     123661
31.0       8368
30.0       7712
28.0       7687
29.0       7647
          ...
4.0           3
111.0         2
150.0         1
132.0         1
112.0         1
Name: age, Length: 106, dtype: int64
0

In [12]:
df_all['age'].quantile(0.5)

33.0

In [13]:
#pd.mean(df_all['age'])
#pd.DataFrame.mean(df_all['age'])

In [14]:
#df_all['age'] = np.where(df_all['age'] > 110, 34, df_all['age'])
#df_all['age'].describe()

In [15]:
by_signup_device = df_all.groupby(['signup_method', 'first_device_type'])

In [16]:
def impute_median(series):
    return series.fillna(series.median())

In [17]:
df_all.age = by_signup_device['age'].transform(impute_median)

In [18]:
df_all['first_affiliate_tracked'].value_counts()

untracked        143181
linked            62064
omg               54859
tracked-other      6655
product            2353
marketing           281
local ops            69
Name: first_affiliate_tracked, dtype: int64

In [19]:
tracked = []

for i in df_all['first_affiliate_tracked']:
    if i == "untracked" or i == "":
        isTracked = 0
    else:
        isTracked = 1
    tracked.append(isTracked)

df_all['is_first_affiliate_tracked'] = tracked

In [20]:
df_all.isnull().sum()

id                                 0
date_first_booking            186639
gender                             0
age                                0
signup_method                      0
signup_flow                        0
language                           0
affiliate_channel                  0
affiliate_provider                 0
first_affiliate_tracked         6085
signup_app                         0
first_device_type                  0
first_browser                      0
dac_year                           0
dac_month                          0
dac_day                            0
tfa_year                           0
tfa_month                          0
tfa_day                            0
is_first_affiliate_tracked         0
dtype: int64

In [21]:
#df_all['created_after_active'].describe()

In [22]:
df_all = df_all.rename(columns={"id":"user_id"})

In [23]:
sessions.user_id.value_counts()

mxqbh3ykxl    2722
0hjoc5q8nf    2644
mjbl6rrj52    2476
l5lgm3w5pc    2424
wg9413iaux    2362
              ...
k0wyihrbd6       1
nzkwb7xqn9       1
fcczt7i196       1
s2qavb275i       1
zlovzkk884       1
Name: user_id, Length: 135483, dtype: int64

In [24]:
seconds = sessions.groupby('user_id', as_index=False).agg({"secs_elapsed": "sum"})
seconds.head()

      user_id  secs_elapsed
0  00023iyk9l      867896.0
1  0010k6l0om      586543.0
2  001wyh0pz8      282965.0
3  0028jgx1x1      297010.0
4  002qnbzfs5     6487080.0

In [25]:
df_all = pd.merge(df_all, seconds, on="user_id", how="left")

In [26]:
df_all.head()

,user_id,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,...,first_device_type,first_browser,dac_year,dac_month,dac_day,tfa_year,tfa_month,tfa_day,is_first_affiliate_tracked,secs_elapsed
0,gxn3p5htnn,NaT,-unknown-,33.0,facebook,0,en,direct,direct,untracked,...,Mac Desktop,Chrome,2010,6,28,2009,3,19,0,NaN
1,820tgsjxq7,NaT,MALE,38.0,facebook,0,en,seo,google,untracked,...,Mac Desktop,Chrome,2011,5,25,2009,5,23,0,NaN
2,4ft3gnwmtx,2010-08-02,FEMALE,56.0,basic,3,en,direct,direct,untracked,...,Windows Desktop,IE,2010,9,28,2009,6,9,0,NaN
3,bjjt8pjhuk,2012-09-08,FEMALE,42.0,facebook,0,en,direct,direct,untracked,...,Mac Desktop,Firefox,2011,12,5,2009,10,31,0,NaN
4,87mebub9p4,2010-02-18,-unknown-,41.0,basic,0,en,direct,direct,untracked,...,Mac Desktop,Chrome,2010,9,14,2009,12,8,0,NaN

In [27]:
df_all['secs_elapsed'] = df_all['secs_elapsed'].fillna(0)

In [28]:
df_all.head()

,user_id,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,...,first_device_type,first_browser,dac_year,dac_month,dac_day,tfa_year,tfa_month,tfa_day,is_first_affiliate_tracked,secs_elapsed
0,gxn3p5htnn,NaT,-unknown-,33.0,facebook,0,en,direct,direct,untracked,...,Mac Desktop,Chrome,2010,6,28,2009,3,19,0,0.0
1,820tgsjxq7,NaT,MALE,38.0,facebook,0,en,seo,google,untracked,...,Mac Desktop,Chrome,2011,5,25,2009,5,23,0,0.0
2,4ft3gnwmtx,2010-08-02,FEMALE,56.0,basic,3,en,direct,direct,untracked,...,Windows Desktop,IE,2010,9,28,2009,6,9,0,0.0
3,bjjt8pjhuk,2012-09-08,FEMALE,42.0,facebook,0,en,direct,direct,untracked,...,Mac Desktop,Firefox,2011,12,5,2009,10,31,0,0.0
4,87mebub9p4,2010-02-18,-unknown-,41.0,basic,0,en,direct,direct,untracked,...,Mac Desktop,Chrome,2010,9,14,2009,12,8,0,0.0

In [29]:
#df_all['datetime_account_created'].dayofweek()

In [30]:
df_all['is_first_affiliate_tracked'].isna().sum()

0

In [31]:
df_all.gender.unique()

array(['-unknown-', 'MALE', 'FEMALE', 'OTHER'], dtype=object)

In [32]:
df_all

,user_id,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,...,first_device_type,first_browser,dac_year,dac_month,dac_day,tfa_year,tfa_month,tfa_day,is_first_affiliate_tracked,secs_elapsed
0,gxn3p5htnn,NaT,-unknown-,33.0,facebook,0,en,direct,direct,untracked,...,Mac Desktop,Chrome,2010,6,28,2009,3,19,0,0.0
1,820tgsjxq7,NaT,MALE,38.0,facebook,0,en,seo,google,untracked,...,Mac Desktop,Chrome,2011,5,25,2009,5,23,0,0.0
2,4ft3gnwmtx,2010-08-02,FEMALE,56.0,basic,3,en,direct,direct,untracked,...,Windows Desktop,IE,2010,9,28,2009,6,9,0,0.0
3,bjjt8pjhuk,2012-09-08,FEMALE,42.0,facebook,0,en,direct,direct,untracked,...,Mac Desktop,Firefox,2011,12,5,2009,10,31,0,0.0
4,87mebub9p4,2010-02-18,-unknown-,41.0,basic,0,en,direct,direct,untracked,...,Mac Desktop,Chrome,2010,9,14,2009,12,8,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275542,cv0na2lf5a,NaT,-unknown-,31.0,basic,0,en,direct,direct,untracked,...,Windows Desktop,IE,2014,9,30,2014,9,30,0,2534232.0
275543,zp8xfonng8,NaT,-unknown-,33.0,basic,23,ko,direct,direct,untracked,...,Android Phone,-unknown-,2014,9,30,2014,9,30,0,51618.0
275544,fa6260ziny,NaT,-unknown-,33.0,basic,0,de,direct,direct,linked,...,Windows Desktop,Firefox,2014,9,30,2014,9,30,1,823297.0
275545,87k0fy4ugm,NaT,-unknown-,33.0,basic,0,en,sem-brand,google,omg,...,Mac Desktop,Safari,2014,9,30,2014,9,30,1,352068.0
275546,9uqfg8txu3,NaT,FEMALE,49.0,basic,0,en,other,other,tracked-other,...,Windows Desktop,Chrome,2014,9,30,2014,9,30,1,2804544.0

In [33]:
list(df_all.columns)

['user_id',
 'date_first_booking',
 'gender',
 'age',
 'signup_method',
 'signup_flow',
 'language',
 'affiliate_channel',
 'affiliate_provider',
 'first_affiliate_tracked',
 'signup_app',
 'first_device_type',
 'first_browser',
 'dac_year',
 'dac_month',
 'dac_day',
 'tfa_year',
 'tfa_month',
 'tfa_day',
 'is_first_affiliate_tracked',
 'secs_elapsed']

In [34]:
#columns = []

In [35]:
#df_all['day_account_created'] = df_all['datetime_account_created'].dt.day_name()
#df_all['day_first_active'] = df_all['datetime_first_active'].dt.day_name()

In [36]:
#day_acct_created = pd.get_dummies(df_all['day_account_created'])
#day_first_active = pd.get_dummies(df_all['day_first_active'])

In [37]:
#day_acct_created = day_acct_created.rename(columns={"Monday": "acct_created_Mon", "Tuesday": "acct_created_Tues", "Wednesday": "acct_created_Wed",
 #                               "Thursday": "acct_created_Thurs", "Friday": "acct_created_Fri", "Saturday": "acct_created_Sat", 
 #                                "Sunday": "acct_created_Sun"})
#day_first_active = day_first_active.rename(columns={"Monday": "first_active_Mon", "Tuesday": "first_active_Tues", "Wednesday": "first_active_Wed",
#                                "Thursday": "first_active_Thurs", "Friday": "first_active_Fri", "Saturday": "first_active_Sat", 
#                                 "Sunday": "first_active_Sun"})

In [38]:
#df_all = pd.concat([df_all.reset_index(drop=True),day_acct_created.reset_index(drop=True)], axis=1)
#df_all = pd.concat([df_all.reset_index(drop=True),day_first_active.reset_index(drop=True)], axis=1)

In [39]:
method = pd.get_dummies(df_all[["signup_method"]])
affch = pd.get_dummies(df_all[["affiliate_channel"]])
affprov = pd.get_dummies(df_all[["affiliate_provider"]])
firstdevice = pd.get_dummies(df_all[["first_device_type"]])
signupFlow = pd.get_dummies(df_all[["signup_flow"]].astype(str))
signup = pd.get_dummies(df_all[["signup_app"]])
genderdum = pd.get_dummies(df_all[["gender"]])
langdum = pd.get_dummies(df_all[["language"]])
browser = pd.get_dummies(df_all[["first_browser"]])

In [40]:
df2 = df_all

In [41]:
signupFlow

,signup_flow_0,signup_flow_1,signup_flow_10,signup_flow_12,signup_flow_14,signup_flow_15,signup_flow_16,signup_flow_2,signup_flow_20,signup_flow_21,signup_flow_23,signup_flow_24,signup_flow_25,signup_flow_3,signup_flow_4,signup_flow_5,signup_flow_6,signup_flow_8
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275542,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
275543,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
275544,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
275545,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
275546,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [42]:
df2 = pd.concat([df2.reset_index(drop=True),method.reset_index(drop=True)], axis=1)
df2 = pd.concat([df2.reset_index(drop=True),affch.reset_index(drop=True)], axis=1)
df2 = pd.concat([df2.reset_index(drop=True),affprov.reset_index(drop=True)], axis=1)
df2 = pd.concat([df2.reset_index(drop=True),firstdevice.reset_index(drop=True)], axis=1)
df2 = pd.concat([df2.reset_index(drop=True),signupFlow.reset_index(drop=True)], axis=1)
df2 = pd.concat([df2.reset_index(drop=True),genderdum.reset_index(drop=True)], axis=1)
df2 = pd.concat([df2.reset_index(drop=True),signup.reset_index(drop=True)], axis=1)
df2 = pd.concat([df2.reset_index(drop=True),langdum.reset_index(drop=True)], axis=1)
df2 = pd.concat([df2.reset_index(drop=True),browser.reset_index(drop=True)], axis=1)

In [43]:
missing_values_table(df2)

Your selected dataframe has 167 columns.
There are 2 columns that have missing values.

                         Missing Values  % of Total Values
date_first_booking               186639               67.7
first_affiliate_tracked            6085                2.2

In [44]:
list(df2.columns)

['user_id',
 'date_first_booking',
 'gender',
 'age',
 'signup_method',
 'signup_flow',
 'language',
 'affiliate_channel',
 'affiliate_provider',
 'first_affiliate_tracked',
 'signup_app',
 'first_device_type',
 'first_browser',
 'dac_year',
 'dac_month',
 'dac_day',
 'tfa_year',
 'tfa_month',
 'tfa_day',
 'is_first_affiliate_tracked',
 'secs_elapsed',
 'signup_method_basic',
 'signup_method_facebook',
 'signup_method_google',
 'signup_method_weibo',
 'affiliate_channel_api',
 'affiliate_channel_content',
 'affiliate_channel_direct',
 'affiliate_channel_other',
 'affiliate_channel_remarketing',
 'affiliate_channel_sem-brand',
 'affiliate_channel_sem-non-brand',
 'affiliate_channel_seo',
 'affiliate_provider_baidu',
 'affiliate_provider_bing',
 'affiliate_provider_craigslist',
 'affiliate_provider_daum',
 'affiliate_provider_direct',
 'affiliate_provider_email-marketing',
 'affiliate_provider_facebook',
 'affiliate_provider_facebook-open-graph',
 'affiliate_provider_google',
 'affiliate_provider_gsp',
 'affiliate_provider_meetup',
 'affiliate_provider_naver',
 'affiliate_provider_other',
 'affiliate_provider_padmapper',
 'affiliate_provider_vast',
 'affiliate_provider_wayn',
 'affiliate_provider_yahoo',
 'affiliate_provider_yandex',
 'first_device_type_Android Phone',
 'first_device_type_Android Tablet',
 'first_device_type_Desktop (Other)',
 'first_device_type_Mac Desktop',
 'first_device_type_Other/Unknown',
 'first_device_type_SmartPhone (Other)',
 'first_device_type_Windows Desktop',
 'first_device_type_iPad',
 'first_device_type_iPhone',
 'signup_flow_0',
 'signup_flow_1',
 'signup_flow_10',
 'signup_flow_12',
 'signup_flow_14',
 'signup_flow_15',
 'signup_flow_16',
 'signup_flow_2',
 'signup_flow_20',
 'signup_flow_21',
 'signup_flow_23',
 'signup_flow_24',
 'signup_flow_25',
 'signup_flow_3',
 'signup_flow_4',
 'signup_flow_5',
 'signup_flow_6',
 'signup_flow_8',
 'gender_-unknown-',
 'gender_FEMALE',
 'gender_MALE',
 'gender_OTHER',
 'signup_app_Android',
 'signup_app_Moweb',
 'signup_app_Web',
 'signup_app_iOS',
 'language_-unknown-',
 'language_ca',
 'language_cs',
 'language_da',
 'language_de',
 'language_el',
 'language_en',
 'language_es',
 'language_fi',
 'language_fr',
 'language_hr',
 'language_hu',
 'language_id',
 'language_is',
 'language_it',
 'language_ja',
 'language_ko',
 'language_nl',
 'language_no',
 'language_pl',
 'language_pt',
 'language_ru',
 'language_sv',
 'language_th',
 'language_tr',
 'language_zh',
 'first_browser_-unknown-',
 'first_browser_AOL Explorer',
 'first_browser_Android Browser',
 'first_browser_Apple Mail',
 'first_browser_Arora',
 'first_browser_Avant Browser',
 'first_browser_BlackBerry Browser',
 'first_browser_Camino',
 'first_browser_Chrome',
 'first_browser_Chrome Mobile',
 'first_browser_Chromium',
 'first_browser_CometBird',
 'first_browser_Comodo Dragon',
 'first_browser_Conkeror',
 'first_browser_CoolNovo',
 'first_browser_Crazy Browser',
 'first_browser_Epic',
 'first_browser_Firefox',
 'first_browser_Flock',
 'first_browser_Google Earth',
 'first_browser_Googlebot',
 'first_browser_IBrowse',
 'first_browser_IE',
 'first_browser_IE Mobile',
 'first_browser_IceDragon',
 'first_browser_IceWeasel',
 'first_browser_Iron',
 'first_browser_Kindle Browser',
 'first_browser_Maxthon',
 'first_browser_Mobile Firefox',
 'first_browser_Mobile Safari',
 'first_browser_Mozilla',
 'first_browser_NetNewsWire',
 'first_browser_Nintendo Browser',
 'first_browser_OmniWeb',
 'first_browser_Opera',
 'first_browser_Opera Mini',
 'first_browser_Opera Mobile',
 'first_browser_Outlook 2007',
 'first_browser_PS Vita browser',
 'first_browser_Pale Moon',
 'first_browser_Palm Pre web browser',
 'first_browser_RockMelt',
 'first_browser_Safari',
 'first_browser_SeaMonkey',
 'first_browser_Silk',
 'first_browser_SiteKiosk',
 'first_browser_SlimBrowser',
 'first_browser_Sogou Explorer',
 'first_browser_Stainless',
 'first_browser_TenFourFox',
 'first_browser_TheWorld Browser',
 'first_browser_UC Browser',
 'first_browser_Yandex.Browser',
 'first_browser_wOSBrowser']

In [45]:
#columns_to_drop = ['user_id', 'date_account_created', 'timestamp_first_active', 'date_first_booking',
#'gender', 'signup_method', 'signup_flow',affiliate_channel, affiliate_provider, 
#first_device_type, first_browser, signup_app
df2 = df2.drop(['user_id',  'date_first_booking','gender', 
          'signup_method',  'affiliate_channel', 'affiliate_provider', 'first_device_type', 
          'first_browser', 'signup_app', 'first_browser'], axis=1)

In [46]:
df2.head(5)
df2 = df2.drop('language', axis=1)

In [47]:
df2 = df2.drop('signup_flow', axis=1)

In [48]:
df2

,age,first_affiliate_tracked,dac_year,dac_month,dac_day,tfa_year,tfa_month,tfa_day,is_first_affiliate_tracked,secs_elapsed,...,first_browser_Silk,first_browser_SiteKiosk,first_browser_SlimBrowser,first_browser_Sogou Explorer,first_browser_Stainless,first_browser_TenFourFox,first_browser_TheWorld Browser,first_browser_UC Browser,first_browser_Yandex.Browser,first_browser_wOSBrowser
0,33.0,untracked,2010,6,28,2009,3,19,0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,38.0,untracked,2011,5,25,2009,5,23,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,56.0,untracked,2010,9,28,2009,6,9,0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,42.0,untracked,2011,12,5,2009,10,31,0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,41.0,untracked,2010,9,14,2009,12,8,0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275542,31.0,untracked,2014,9,30,2014,9,30,0,2534232.0,...,0,0,0,0,0,0,0,0,0,0
275543,33.0,untracked,2014,9,30,2014,9,30,0,51618.0,...,0,0,0,0,0,0,0,0,0,0
275544,33.0,linked,2014,9,30,2014,9,30,1,823297.0,...,0,0,0,0,0,0,0,0,0,0
275545,33.0,omg,2014,9,30,2014,9,30,1,352068.0,...,0,0,0,0,0,0,0,0,0,0
275546,49.0,tracked-other,2014,9,30,2014,9,30,1,2804544.0,...,0,0,0,0,0,0,0,0,0,0

In [49]:
#df2 = df2.drop(['first_affiliate_tracked', 'datetime_first_active', 'datetime_account_created'] ,axis=1)

In [50]:
#df2 = df2.drop(['created_after_active', 'day_account_created', 'day_first_active'] ,axis=1)

In [51]:
df2 = df2.drop(['first_affiliate_tracked'], axis=1)

In [52]:
df2.columns

Index(['age', 'dac_year', 'dac_month', 'dac_day', 'tfa_year', 'tfa_month',
       'tfa_day', 'is_first_affiliate_tracked', 'secs_elapsed',
       'signup_method_basic',
       ...
       'first_browser_Silk', 'first_browser_SiteKiosk',
       'first_browser_SlimBrowser', 'first_browser_Sogou Explorer',
       'first_browser_Stainless', 'first_browser_TenFourFox',
       'first_browser_TheWorld Browser', 'first_browser_UC Browser',
       'first_browser_Yandex.Browser', 'first_browser_wOSBrowser'],
      dtype='object', length=155)

In [53]:
df2.shape

(275547, 155)

In [54]:
from sklearn import model_selection

train = df2.iloc[0:len(train_users),:]
test = df2.iloc[len(train_users):,:]


X_train, X_test, y_train, y_test = model_selection.train_test_split(train, Y, test_size=0.33, random_state=42)

In [55]:
train.columns

Index(['age', 'dac_year', 'dac_month', 'dac_day', 'tfa_year', 'tfa_month',
       'tfa_day', 'is_first_affiliate_tracked', 'secs_elapsed',
       'signup_method_basic',
       ...
       'first_browser_Silk', 'first_browser_SiteKiosk',
       'first_browser_SlimBrowser', 'first_browser_Sogou Explorer',
       'first_browser_Stainless', 'first_browser_TenFourFox',
       'first_browser_TheWorld Browser', 'first_browser_UC Browser',
       'first_browser_Yandex.Browser', 'first_browser_wOSBrowser'],
      dtype='object', length=155)

In [56]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62096 entries, 213451 to 275546
Columns: 155 entries, age to first_browser_wOSBrowser
dtypes: float64(2), int64(7), uint8(146)
memory usage: 12.9 MB

In [57]:
from xgboost.sklearn import XGBClassifier
xgb = XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.5, gamma=0, 
                    gpu_id=-1, importance_type='gain', interaction_constraints=None, 
                    learning_rate=0.3, max_delta_step=0, max_depth=6, min_child_weight=1, 
                    monotone_constraints=None, n_estimators=25, n_jobs=0, num_parallel_tree=1, 
                    objective='multi:softprob', random_state=0, reg_alpha=0, reg_lambda=1, 
                    scale_pos_weight=None, seed=0, subsample=0.5, tree_method=None, 
                    validate_parameters=False, verbosity=None)

In [58]:
model = xgb.fit(train,Y)

In [59]:
model

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.5, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.3, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=25, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, seed=0, subsample=0.5,
              tree_method='exact', validate_parameters=False, verbosity=None)

In [60]:
train.columns

Index(['age', 'dac_year', 'dac_month', 'dac_day', 'tfa_year', 'tfa_month',
       'tfa_day', 'is_first_affiliate_tracked', 'secs_elapsed',
       'signup_method_basic',
       ...
       'first_browser_Silk', 'first_browser_SiteKiosk',
       'first_browser_SlimBrowser', 'first_browser_Sogou Explorer',
       'first_browser_Stainless', 'first_browser_TenFourFox',
       'first_browser_TheWorld Browser', 'first_browser_UC Browser',
       'first_browser_Yandex.Browser', 'first_browser_wOSBrowser'],
      dtype='object', length=155)

In [61]:
from sklearn.metrics import ndcg_score

model.score(train, Y)

0.6379918576160336

In [62]:
y_pred = model.predict(test)

In [63]:
#ndcg_score(y_test, y_pred)

In [64]:
Y_PREDICT = model.predict_proba(test)

In [65]:
id_test = test_users['id']
def generate_answer(y_pred, classifer_name):
    #Taking the 5 classes with highest probabilities
    ids = []  #list of ids
    cts = []  #list of countries
    for i in range(len(id_test)):
        idx = id_test[i]
        ids += [idx] * 5
        cts += le.inverse_transform(np.argsort(y_pred[i])[::-1])[:5].tolist()
    
    sub = pd.DataFrame(np.column_stack((ids, cts)), columns=['id', 'country'])
    sub.to_csv(classifer_name+'.csv',index=False)
    return sub

In [66]:
generate_answer(Y_PREDICT, 'XGB')

NameError: name 'id_test' is not defined

In [ ]:
"""
submission = pd.DataFrame(Y_PREDICT)
test_users = pd.read_csv("proj3_data/test_users.csv")
submission["id"] = test_users["id"]
submission.columns = ['country', 'id']
submission = submission[['id', 'country']]
submission"""

In [ ]:
#submission.to_csv("submission.csv",index=False,)

In [ ]:
"""
from xgboost import plot_importance
from matplotlib import pyplot



sorted_idx = np.argsort(model.feature_importances_)[::-1]
for index in sorted_idx:
    print([train.columns[index], model.feature_importances_[index]]) """

#y = model.get_booster().get_score()

#scores = pd.DataFrame(y)
#scores
#print(model.feature_importances_)
#print(y)
"""
y = plot_importance(model, xlim=(0,2000))
print(y)
y = model.get
#pyplot.show()"""